name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run test script
      run: echo "Running test script"
